# This is the configuration file for the Drill machine. #
# A full list of materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html #
# ================================================================== #
# &b : AQUA
# &0 : BLACK
# &9 : BLUE
# &l : BOLD
# &3 : DARK_AQUA
# &1 : DARK_BLUE
# &8 : DARK_GRAY
# &2 : DARK_GREEN
# &5 : DARK_PURPLE
# &4 : DARK_RED
# &6 : GOLD
# &7 : GRAY
# &a : GREEN
# &o : ITALIC
# &d : LIGHT_PURPLE
# &k : MAGIC
# &c : RED
# &r : RESET
# &m : STRIKETHROUGH
# &n : UNDERLINE
# &f : WHITE
# &e : YELLOW

machine:
    # This controls whether drills will be allowed on the server at all #
    enabled: true
    # These control how drills inventories are created #
    inventory:
        name: 'Drill'
        rows: 1
    # This is used to set the drill item information #
    item:
        type: 'PISTON'
        name: '&6Drill'
        lore:
            - "&f&o'It looks very old and heavy'"
            - "&7Requires fuel"
    # This controls the recipe to craft drills #
    crafting:
        shape: ['RPR', 'RFR', 'IOI']
        mapping:
            R: 'BLAZE_ROD'
            P: 'PISTON'
            F: 'FURNACE'
            I: 'IRON_PICKAXE'
            O: 'OBSIDIAN'
    # This controls how fast drills operate. (20 ticks = 1 second) Larger numbers make drills operate slower #
    speedInTicks: 10
    # This controls whether the drill will fill empty buckets in its inventory when encountering water/lava #
    fillBuckets: true
    # The number represents how many blocks the machine will mine per fuel #
    fuelTypes:
        COAL: 10
        CHARCOAL: 10
        LAVA_BUCKET: 100
        BLAZE_ROD: 30
        LOGS: 4
        PLANKS: 1
    # This is the message that is sent to players who try to start machines that do not have fuel #
    fuelMessage: "&7The drill needs fuel in order to start."
    # These are the sound effects that play when the machine does an action #
    soundEffects:
        turnOn: BLOCK_NOTE_BLOCK_HAT
        turnOff: ENTITY_BLAZE_HURT
        rotate: BLOCK_PISTON_CONTRACT
        work1: BLOCK_PISTON_EXTEND
        work2: BLOCK_PISTON_CONTRACT
    # These are the materials that drills cannot break, and will halt when running into them #
    blockBlacklist:
        - ARMOR_STAND
        - BARRIER
        - BEACON
        - RED_BED
        - BREWING_STAND
        - BEDROCK
        - COMMAND_BLOCK
        - CHEST
        - DISPENSER
        - DROPPER
        - ENCHANTING_TABLE
        - ENDER_CHEST
        - FURNACE
        - PISTON
        - PISTON_HEAD
        - MOVING_PISTON
        - STICKY_PISTON
        - TRAPPED_CHEST
