# This is the configuration file for the Paver machine. #
# A full list of materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html #
# ================================================================== #
# &b : AQUA
# &0 : BLACK
# &9 : BLUE
# &l : BOLD
# &3 : DARK_AQUA
# &1 : DARK_BLUE
# &8 : DARK_GRAY
# &2 : DARK_GREEN
# &5 : DARK_PURPLE
# &4 : DARK_RED
# &6 : GOLD
# &7 : GRAY
# &a : GREEN
# &o : ITALIC
# &d : LIGHT_PURPLE
# &k : MAGIC
# &c : RED
# &r : RESET
# &m : STRIKETHROUGH
# &n : UNDERLINE
# &f : WHITE
# &e : YELLOW

machine:
    # This controls whether pavers will be allowed on the server at all #
    enabled: true
    # These control how pavers inventories are created #
    inventory:
        name: 'Paver'
        rows: 1
    # This is used to set the paver item information #
    item:
        type: 'DISPENSER'
        name: '&6Paver'
        lore:
            - "&f&o'Very rusty with loose parts'"
            - "&7Requires fuel"
    # This controls the recipe to craft pavers #
    crafting:
        shape: ['RDR', 'RFR', 'BOB']
        mapping:
            R: 'BLAZE_ROD'
            D: 'DISPENSER'
            F: 'FURNACE'
            B: 'REDSTONE_BLOCK'
            O: 'OBSIDIAN'
    # This controls how fast pavers operate. (20 ticks = 1 second) Larger numbers make pavers operate slower #
    speedInTicks: 10
    # The number represents how many blocks the machine will place down per fuel #
    fuelTypes:
        COAL: 10
        CHARCOAL: 10
        LAVA_BUCKET: 100
        BLAZE_ROD: 30
        LOGS: 4
        PLANKS: 1
    # This is the message that is sent to players who try to start machines that do not have fuel #
    fuelMessage: "&7The paving machine needs fuel in order to start."
    # These are the sound effects that play when the machine does an action #
    soundEffects:
        turnOn: BLOCK_NOTE_BLOCK_HAT
        turnOff: ENTITY_BLAZE_HURT
        rotate: BLOCK_PISTON_CONTRACT
        work1: BLOCK_PISTON_EXTEND
        work2: BLOCK_PISTON_CONTRACT
    # These are the materials that pavers will pave over #
    blockWhitelist:
        - AIR
        - BROWN_MUSHROOM
        - DEAD_BUSH
        - FIRE
        - LAVA
        - WATER
        - TALL_GRASS
        - RED_MUSHROOM
        - POPPY
        - SNOW
        - VINE
        - DANDELION