name: Machines
author: Tanner Embry
description: Build and use different machines in Minecraft!
version: 1.0
main: com.snowgears.machines.Machines
permissions:
    machines.gravity.use:
        description: Allows player to use antigrav machines
        default: op
    machines.miner.use:
        description: Allows player to use antigrav machines
        default: op
    machines.pump.use:
        description: Allows player to use antigrav machines
        default: op
    machines.operator:
        description: Allows all operator functionality within the plugin
        default: op
commands:
   machines:
      description: Different commands pertaining to plugin
      usage: /<command>